version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      otel:
        patterns:
          - "*opentelemetry.io*"
      prom:
        patterns:
          - "*prometheus*"
      k8s:
        patterns:
          - "*k8s.io*"
      ginkgo:
        patterns:
          - "*onsi*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
